export const endpoints = {
  role: { getAll: "/api/role" },
  status: { getAll: "/api/status/getAllStatus" },
  auth: {
    login: "/api/auth/loginUser",
  },
  address: {
    regions: {
      getAll: "/api/region/getAllRegions",
      getById: "/api/region/getRegionById/",
      post: "/api/region/addRegion",
      put: "/api/region/editRegion/",
      delete: "/api/region/deleteRegion/",
    },
    subRegions: {
      getAll: "/api/subRegion/getAllSubRegions",
      getByParentId: "/api/subRegion/getSubRegionsByRegionId/",
      post: "/api/subRegion/addSubRegion",
      put: "/api/subRegion/editSubRegion/",
      delete: "/api/subRegion/deleteSubRegion/",
    },
    postFilials: {
      getAll: "/api/postFilial/getAllPostFilial",
      post: "/api/postFilial/addPostFilial",
      put: "/api/postFilial/editPostFilial/",
      delete: "/api/postFilial/deletePostFilial/",
    },
  },
  brand: {
    getAll: "/api/brand/getAllBrands",
    post: "/api/brand/addBrand",
    put: "/api/brand/editBrand/",
    delete: "/api/brand/deleteBrand/",
  },
  category: {
    getAll: "/api/categories/getAllCategories",
    getParent: "/api/categories/getParentCategories",
    getSub: "/api/categories/getSubCategories",
    getSubByParentName: "/api/categories/getSubCategoriesByParent/",
    post: "/api/categories/addCategory",
    put: "/api/categories/editCategory/",
    delete: "/api/categories/deleteCategory/",
    block: {
      getAll: "/api/categoryBlock/getAllCategoryBlocks",
      getAllByType: "/api/categoryBlock/getAllByCategoryBlockType/",
      post: "/api/categoryBlock/addCategoryBlock",
      put: "/api/categoryBlock/editCategoryBlock/",
    },
  },
  color: {
    getAll: "/api/color/getAllColors",
    post: "/api/color/addColor",
    put: "/api/color/editColor/",
    delete: "/api/color/deleteColor/",
  },
  coupon: {
    getAll: "/api/coupon/getAllCoupons",
    getByEnumNames: "/api/coupon/enums/couponNames",
    post: "/api/coupon/addCoupon",
    put: "/api/coupon/editCoupon/",
    delete: "/api/coupon/deleteCoupon/",
  },
  users: {
    getAll: "/api/customers/getAll",
    userDelete: "/api/customers/delete/",
    useById: "/api/customers/getCustomerById/",
  },
  admins: {
    getAll: "/api/users/geAllUser",
    post: "/api/users/add",
    put: "/api/users/editUser/",
    delete: "/api/users/deleteUser/",
  },
  look: {
    getAll: "/api/lookCollection/getLookCollection",
    getById: "/api/lookCollection/getLookCollectionById/",
    post: "/api/lookCollection/addLookCollection",
    delete: "/api/lookCollection/deleteLookCollectionById/",
  },
  sale: {
    getAll: "/api/saleGroup/getAllSaleGroups",
    post: "/api/saleGroup/addSaleGroup",
    delete: "/api/saleGroup/removeSaleGroup", // POST body bilan { saleGroupId, saleCategoryId }
  },
  sms: {
    getAll: "/api/sms/getAll",
    getTemplateNames: "/api/sms/enums/smsNames",
    post: "/api/sms/add",
    put: "/api/sms/edit/", // + tempSmsName
  },
  karusel: {
    getAll: "/api/karusel/getAllKarusels",
    post: "/api/karusel/addKarusel",
    delete: "/api/karusel/deleteKarusel/",
  },
  smallSlider: {
    getAll: "/api/smallSlider/getAllSmallSliders",
    getByPlaceNumber: "/api/smallSlider/getByPlaceNumber/",
    post: "/api/smallSlider/addSmallSlider",
    put: "/api/smallSlider/editSmallSlider/",
    delete: "/api/smallSlider/deleteSmallSlider/",
  },
  products: {
    getAll: "/api/product/getAllProducts",
    getById: "/api/product/getProductById/",
    getAllAvtive: "/api/product/getAllActiveProducts",
    getByRefNumber: "/api/product/searchProduct/",
    post: "/api/product/addProduct",
    put: "/api/product/editProduct/",
    putByRefNumber: "/api/product/editRefnumber/",
    delete: "/api/product/deleteProduct/",
  },
  order: {
    getAll: "/api/order/getAllOrders",
    getAllPaid: "/api/order/getAllOrdersPaidIsTrue",
    getAllDelivered: "/api/order/getReachedOrders",
    getNew: "/api/order/getNewOrders",
    getCanceled: "/api/order/getRejectedOrders",
    getShipped: "/api/order/getSendOrders",
    getPackaged: "/api/order/getPackOrders",
    getById: "/api/order/getOrderById/",
    putToPack: "/api/order/editStatusToPack/",
    putToRejected: "/api/order/editStatusToRejected/",
    putToReached: "/api/order/editStatusToReached/",
    putToSend: "/api/order/editStatusToSend/",
  },
  notifications: {
    getById: "/api/notification/getNotificationsForCustomer/",
    postAll: "/api/notification/addNotificationToAll",
    postToUser: "/api/notification/addNotificationToCustomer",
  },
  review: {
    reviewAll: "/api/review/getAllReviews",
    reviewDelete: "/api/review/deleteReview/",
    reviewModerate: "/api/review/moderateReview",
  },
  payment: {
    getAll: "/payment/getAllPayments",
    getByDate: "/payment/by-date",
  },
};
